### ISSUE TITLE
Include MacOS builds

### ISSUE THREAD

**Issue by themaster567** [AtomicFox556/Cataclysm-EOD#145]
### Is your feature request related to a problem? Please describe.

There is currently not a MacOS build.

### Solution you would like.

A MacOS build to be included alongside the Windows and Linux builds.

### Describe alternatives you have considered.

Compile personally for myself. I am currently doing this already.

**Comment by AtomicFox556** [comment]
MacOS builds are already enabled, but it appears that they're for some reason omitted from the majority of releases. The last one that is available (specifically the tiles version) is https://github.com/AtomicFox556/Cataclysm-EOD/releases/tag/eod-experimental-2023-12-07-0808.

I suspect that it may be related to overall compilation time limitation, though DDA releases don't seem to have this issue.

**Comment by themaster567** [comment]
That's strange, but at least there's an answer! I'll use the build you've linked until it's compiling again. I was having too many issues getting the app actually build properly (running via command line inside of the folder worked fine but that wasn't as ideal), not to mention needing to download nearly 7 GB of data to make a 100 MB compilation was a bit taxing for my poor connection.
