### ISSUE TITLE
MacOS builds

### ISSUE THREAD

**Issue by DazedNConfused-** [AtomicFox556/Cataclysm-EOD#148]
### Is your feature request related to a problem? Please describe.

This is a duplicate of https://github.com/AtomicFox556/Cataclysm-EOD/issues/145, which was marked as stale but is still very much a problem that is still occurring.

### Solution you would like.

MacOS artifacts to be restored as expected binaries in the release process.

**Comment by DazedNConfused-** [comment]
I am not well versed in CDDA's build process, nor it's MacOS related intrincancies. But I spot an error that may or may not be related to this issue in https://github.com/AtomicFox556/Cataclysm-EOD/actions/runs/7780163294/job/21212413665

```
/Applications/Xcode_14.2.app/Contents/Developer/usr/bin/make -C lang
make[1]: Nothing to be done for `all'.
mkdir -p Cataclysm.app/Contents/Resources/lang/mo/
cp -pR lang/mo/* Cataclysm.app/Contents/Resources/lang/mo/
cp -R data/sound Cataclysm.app/Contents/Resources/data
cp -R gfx Cataclysm.app/Contents/Resources/
cp -R /Users/runner/Library/Frameworks/SDL2.framework Cataclysm.app/Contents/Resources/
cp -R /Users/runner/Library/Frameworks/SDL2_image.framework Cataclysm.app/Contents/Resources/
cp -R /Users/runner/Library/Frameworks/SDL2_ttf.framework Cataclysm.app/Contents/Resources/
cp -R /Users/runner/Library/Frameworks/SDL2_mixer.framework Cataclysm.app/Contents/Resources/
plutil -convert binary1 Cataclysm.app/Contents/Info.plist
dmgbuild -s build-data/osx/dmgsettings.py "Cataclysm DDA" Cataclysm.dmg
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/dmgbuild", line 7, in <module>
    import dmgbuild
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/__init__.py", line 1, in <module>
    from .core import build_dmg
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/core.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
make: *** [dmgdist] Error 1
Error: Process completed with exit code 2.
```

**Comment by AtomicFox556** [comment]
I am aware of this issue; previous one was marked stale and later close by the bot.

I am not famillar with the build process of MacOS (and neither I have a suitable device to try to figure it out), so I don't really know how to fix this; help would be appreciated.

**Comment by DazedNConfused-** [comment]
Seems like the PR's related build managed to produce the tiles MacOS artifact. The curses one failed to detach the device cleanly

```
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
hdiutil: couldn't eject "disk6" - Resource busy
hdiutil: couldn't eject "disk6" - Resource busy
hdiutil: couldn't eject "disk6" - Resource busy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/dmgbuild", line 36, in <module>
    dmgbuild.build_dmg(args.filename, args.volume_name, args.settings, defines=defines, lookForHiDPI=args.lookForHiDPI)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/core.py", line 614, in build_dmg
    raise DMGError('Unable to detach device cleanly')
dmgbuild.core.DMGError: Unable to detach device cleanly
```

that is a MacOS problem that I have seen happening once before, in a different pipeline, and with a rerun the second time succeeded. So I wouldn't worry too much about it yet.

What does worry me though, is something unrelated to the change, or this ticket for that matter: the Windows builds are failing:

<img width="297" alt="image" src="https://github.com/AtomicFox556/Cataclysm-EOD/assets/6098622/75cecd9e-df6e-4510-a4a6-d4c397081062">

That is something that I have seen in my own branch, but I had dismissed it as a problem inherent to my fork and nothing else. Seems like there may be another issue there...
