### ISSUE TITLE
India/South Asia regional mods/world settings

### ISSUE THREAD

**Issue by Mustelon** [AtomicFox556/Cataclysm-EOD#57]
### Is your feature request related to a problem? Please describe.

I've always found myself lost in meditation and wanderlust playing Cataclysm: DDA, wondering... what is the world like beyond New England, and North America?

Several of friends of mine are from this region and I've always wanted to have a post-apocalypse game set in South Asia, instead of the usual USA or former USSR.

### Solution you would like.

Regional mods for settings and options related to creating an EOD experience bring post-apocalypse survival, trade, building, exploration, fighting, etc. from New England to India and other South Asian countries.

### Describe alternatives you have considered.

Focusing on developing EOD content for a more fleshed out New England, and focus on the USA regions for now starting from the NE Atlantic Seaboard.

### Additional context

Have never programmed or used Github or C++ or Python or JSON before. These are all unknown skills and uncharted territory to me.

**Comment by AtomicFox556** [comment]
It will happen someday, though myself I'm currently working on other things.

Right now, anyone interested in it could make region-specific locations, items and monsters that could spawn as off-world locations outside of towns, with default game settings.
