### ISSUE TITLE
Fails to compile with -Werror and/or -Wunused-variable

### ISSUE THREAD

**Issue by inverimus** [AtomicFox556/Cataclysm-EOD#80]
### Describe the bug

Fails to compile due to unused variable and -Werror flag.

```
src/handle_liquid.cpp: In function ‘bool liquid_handler::get_liquid_target(item&, const item*, int, const tripoint*, const vehicle*, const monster*, liquid_dest_opt&)’:
src/handle_liquid.cpp:204:11: warning: unused variable ‘phase’ [-Wunused-variable]
  204 |     char *phase = const_cast<char *>( phasestring.c_str() );
      |           ^~~~~
```

### Attach save file

n/a

### Steps to reproduce

Tried to compile with `make -j12 ASTYLE=0 LINTJSON=0 RELEASE=1 CCACHE=1 LUA=1 LTO=1 SOUND=0 LOCALIZE=0 RUNTESTS=0 BACKTRACE=0` with gcc 12.2.1.

### Expected behavior

The game compiles fine without -Werror and I assume without -Wunused-variable as well.

### Versions and configuration

n/a

**Comment by AtomicFox556** [comment]
Thanks for the report, will look into it.

**Comment by AtomicFox556** [comment]
I've made relevant changes in #82 , could you check if this fixed the issue?

**Comment by inverimus** [comment]
Yes, its fixed.
