### ISSUE TITLE
Graphical problems with curses graphics

### ISSUE THREAD

**Issue by inverimus** [AtomicFox556/Cataclysm-EOD#87]
### Describe the bug

Lots of strange graphical glitches when compiled without tiles support. This doesn't happen in DDA.

### Attach save file

N/A

### Steps to reproduce

Compile with TILES=0.

### Expected behavior

N/A

### Screenshots

Red arrows show where tiles are brown instead of correct color. These horizontal areas of incorrect color follow the player. The purple arrow is road and so should be grey.
![ceod1](https://user-images.githubusercontent.com/4513994/232321056-05fa043a-3e3d-4ffe-83d8-ab59fe05c665.png)

This one is more obviously wrong.
![map](https://user-images.githubusercontent.com/4513994/232321062-a38954aa-c93d-48dd-8304-3a2d4bf965d8.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 22.1.0; Codename: Talos;
- Game Version: f55df93d77-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]

**Comment by AtomicFox556** [comment]
Don't know how to fix this. Help would be appreciated.
